version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform

 
    steps:
      - checkout
      - run:
          name: The First Step
          command: ls
      - persist_to_workspace:
          root: ./
          paths: ./
          
workflows:
  version: 2
  workflow:
    jobs:
    - build

