version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform

 
    steps:
      - checkout
      - run:
          name: The First Step
          command: terraform -help
      
          
workflows:
  version: 2
  workflow:
    jobs:
    - build

